### ISSUE TITLE
Webpack for the client code / stylesheets?

### ISSUE THREAD

**Issue by pygy** [socketstream/socketstream-0.4#10]
https://github.com/webpack/webpack
https://github.com/component/component

Webpack is a project similar to Browserify, but much, much more versatile, since it also handles components and style sheets (including preprocessors), and arbitrary files as long as you give it a suitable plugin.

It also handles minification with uglify, and adds only 300 bytes of overhead.

It may be worth a look.

**Comment by jcw** [comment]
Niiiiice! Lots of examples, looks like a very clean and modular approach.

**Comment by owenb** [comment]
Hi @pygy

Already had my eye on component.js for a while, but never knew about webpack. Looks really good.

The key for me is amazing integration with everything we have now: e.g. parsing files in realtime while in dev mode (as we've tried watching files before and it doesn't work well on some platforms), coupling it with Live Reload, and making it possible to load additional client-side code asynchronously.

If we can use some or all of webpack to make a great user experience that would be awesome.

**Comment by jcw** [comment]
Been looking into this just now - good intro at http://webpack.github.com/

It looks excellent to me. It supports "chunking" up things so packages need not all be bundled into one huge file - perfect if you have tons of modules, of which the client might only be requiring a few at any point in time (hint, hint).

**Comment by owenb** [comment]
Webpack looks very good. Thanks for mentioning it. I will look into it closely

**Comment by jcw** [comment]
Or... much leaner option would be https://github.com/azer/onejs#readme

**Comment by jcw** [comment]
Or WebMake on [github](https://github.com/medikoo/modules-webmake) - with an eye towards future ES6 support, see slides 64-up of [this presentation](http://www.slideshare.net/medikoo/javascript-modules-done-right).

_Ok, I'll shut up now ;)_
