### ISSUE TITLE
tutorial - what am I doing wrong?

### ISSUE THREAD

**Issue by tedx** [socketstream/socketstream-0.4#16]
I'm trying to learn by working through the tutorial but am not getting very far. I installed socketstream (sudo npm install -g socketstream) and created app.js and main.html from the tutorial instructions but when I try and run the server I get:

[tedx@localhost sstest]$ node app.js

/home/tedx/sstest/app.js:3
    app = SocketStream();
          ^
TypeError: object is not a function
    at Object.<anonymous> (/home/tedx/sstest/app.js:3:11)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

Have I missed something? I running node 0.10.3.

**Comment by owenb** [comment]
Hey there

I suspect you're doing nothing wrong. The tutorial has just got out of sync with the crazy amount of changes that have taken place over the last few weeks.

I'll go through it over the next few days and update everything. I'm aiming to get all the realtime server stuff stable-ish in time for my talk at Realtime Conf EU on Monday. The asset serving/building part of SocketStream still needs a lot more work but should be stable within the next month or so.

Despite the tutorial not working you should be able to get the example app working. Let me know if you have any problems here.

Cheers,

Owen
