### ISSUE TITLE
Setting up the app for development and setting up our documentation

### ISSUE THREAD

**Issue by arxpoetica** [socketstream/socketstream-0.4#19]
1. Developers need to know how to fork and run the app locally for development purposes so they can make pull requests in the Open Source community. Part of this involves documentation for setting things up. Tangent, but I thought this was interesting: http://paulmillr.com/posts/github-pull-request-stats/
2. Documentation for using SS in general. How do we organize things. Do we run a website (I'd like to do this -- documentation can exist on GitHub _and_ a website using markdown)?

Discuss.

**Comment by RomanMinkin** [comment]
1. ...
2. ...
3. Add tasks based build framework, which will contain:
   - JavaScript syntax linting (jsHint I guess will be better)
   - Tests runner with the options to run separately unit tests and e2e tests 
4. Add `prism` and `socketstream-0.4` to https://travis-ci.org and put links into README.md so projects can have current build statuses <a href="https://travis-ci.org/socketstream/socketstream"><img src="https://api.travis-ci.org/socketstream/socketstream.png" alt="Build Status" style="max-width:100%;"></a>

All that stuff allow easily run linting/tests tasks by contributors to  test theirs changes before sending a pull request  and people who will be able to merge pull request (so they can almost sure that new pull request doesn't break build)

There are two options:
- use existing JavaScript task runner, for ex. http://gruntjs.com/
- or build something like "jake around" stuff ( I use this approach, I like to control everything, but I'm also interesting in Grunt =) )

I'm interested in contributing (i'm using `socketstream-0.3` for my prototype startup project and looking forward into `socketstream-0.4`), so I would be glad to bring this test stuff to live. I can come up with pull request in a week or so.

**Comment by arxpoetica** [comment]
Suggested platforms for documentation? Obviously, it would be super cool to host documentation on SocketStream itself, just to show that it can run. (I wonder if we could get the guys over @ NodeJitsu to sponsor/host our documentation/marketing site, if we promote them...but I digress...)

I'm just going to list out a few options I'm familiar with. Throw in your voice on the yeas or nays.
1. https://github.com/gollum/gollum <-- meh. requires python + ruby
2. https://github.com/flatiron/blacksmith <-- NodeJitsu maintains this, I believe. Very static.
3. http://jashkenas.github.io/docco/ <-- has the benefit of being automated, not sure it's the best choice for API, though

There are also any of these: https://github.com/joyent/node/wiki/modules#wiki-parsers-markdown

Any others?

**Comment by RomanMinkin** [comment]
@americanyak , look like NodeJitsu is free for Open Souce http://opensource.nodejitsu.com/ , but you have to apply.

**Comment by davisford** [comment]
@RomanMinkin I'm a big Grunt fan -- I just went through a process of setting up a solid build system using Grunt + mocha, chai, sinon for tests, and Phantom + Mocha for CI + Google Closure Compiler and JSHint, etc.

I could look into "build-ifying" the current ss repo for automation of a production / debug release as well as test infrastructure.

**Comment by davisford** [comment]
@americanyak Nodejtsu + apply for free access, or just use a free EC2 micro instance.

**Comment by arxpoetica** [comment]
Isn't EC2 only free for a year?

**Comment by paulbjensen** [comment]
+1 for Nodejitsu

**Comment by arxpoetica** [comment]
I sent them an email. Waiting now.

**Comment by davisford** [comment]
With commit access now, I'm interested in doing a branch and setting up a Grunt-based build with test infrastructure, and I'd like to start committing tests to it.  This serves multi-purpose: a) Improve code base through tests - add regression suite, etc. b) Get it hooked into travis-ci like @RomanMinkin suggested c) Allows me to get more familiar with the codebase so I can be in a better position to commit for further dev of ss-0.4.  Once I have the branch in a good state, I'll push it up here for consideration.

**Comment by owenb** [comment]
Very happy to see more tests and things on travis, but if you do want to add Grunt, make sure it's just a devDependency. It's a mammoth dependency and shouldn't be required for 'regular' users.

**Comment by arxpoetica** [comment]
Hey all -- I haven't forgotten my new commitment to this. Just been in the huge thick of a deadline in launching a website on SocketStream. (It's a calculated gamble, knowing some of the things you've said about prod. ready, @owenb). But I just wanted to throw my hat back in the ring that I'll be focused on the task of documentation again soon. The first SS site I built is actually open sourced (https://github.com/engagementgamelab/CivicSeed) and I'm going to be back on that in the coming months, rounding out tests (which we actually never did), among other tasks to stabilize things. It's an SS 3 build, but I hope to eventually migrate to Prism and SS 4, and as part of the documentation effort, I was thinking we could use it as an example of "how to." It's just an idea. In any case, I think I'll be positioned better to be as involved as I want to be.

**Comment by paulbjensen** [comment]
Hi @americanyak,

I've had the same experience, trying to do all the things at the same time is very difficult.

I'm going to have a look at this pull request https://github.com/socketstream/prism/pull/5. I'll be on IRC.

**Comment by davisford** [comment]
I meant to do the same, and added a nearly identical comment as yours to
the pull request.  I believe that the demo rpc example is just following
node api patterns of err as first argument -- in this case, there is
none....don't think we want to pull it.

I had another prism pull request myself -- it's worth discussing at some
point, but I want to make it so you can detach the prism client from the
server (i.e. not require the server to be in place to serve the client, and
thus allow for detached devices running the prism client code to all
connect back to an arbitrary prism server).

I'd like to jump on IRC too -- but it is firewalled during the day where
I'm at right now :(

**Comment by arxpoetica** [comment]
Okay, all, I'm back on SS, as promised. (The SS project I'm working on is on.) Where are y'all at? Still trying to think of a good place to start in on the documentation.

**Comment by arxpoetica** [comment]
Looks like there's a new kid on the block. http://bone.io/#router/middleware I like their documentation. This is sort of what I have in mind, and I think it's critical to build momentum in an open source world.

**Comment by paulbjensen** [comment]
+1 for documentation, should have been done already.
