### ISSUE TITLE
RPC over streams

### ISSUE THREAD

**Issue by jcrugzz** [socketstream/socketstream-0.4#2]
Was reading through the readme and thought I'd recommend [dnode](https://github.com/substack/dnode) for the RPC over streams. Substack seems to know what he's doing with the streams.

Also I'm definitely interested in helping out in my free time. Definitely throw me some little things to get me started or I'll see where I can play a part and throw a pull request.

**Comment by owenb** [comment]
Thanks - would be great!

So my ultimate goal would be to implement the standard streams interface so well you could choose to use Dnode OR the Socketstream RPC module (which includes features for namespacing, meta data, and more) interchangeably.

Still lots to figure out on the stream multiplexing side at the moment, which is what I'm working on right now. Soon as I have anything working I'll commit it.

**Comment by jcrugzz** [comment]
Sweet, sounds good man. I'll keep an eye out for that next commit.

**Comment by owenb** [comment]
Just to let you know, I've made a big commit which gets the initial chat demo working using a new stream-based implementation of the RPC and PubSub components in 0.3.

Next stop is to see how we can use external streams such as DNode and Max Ogden's various browser-based streams (e.g. for sending geolocation data).

**Comment by jcrugzz** [comment]
Awesome, I'll start playing around with it a bit this week.

**Comment by owenb** [comment]
For anyone looking at this in the future, just to let you know I ended up trying Streams2 throughout SocketStream and deciding they weren't worth the additional complexity and massive performance overhead (up to 10x slower than simple callbacks). So I took them out of the code a while back.

**Comment by davisford** [comment]
@owenb I haven't investigated Streams2 myself but do you feel like it is something that will improve -- i.e. is it worth protecting for swapping in the implementation that supports it in the future, or are you pretty much convinced that it won't be feasible b/c of the current limitations?

**Comment by owenb** [comment]
I don't believe it's the right choice for SocketStream. They are too heavy (slow) for what we need. Great for streaming huge files. Not good for small, tiny messages.

Also one-to-many streams in Node are very hard to model. This is why 0.4 was getting so complex before I decided to take them out in January.
