### ISSUE TITLE
Replace Realtime Transport (rtt) idea inside Prism with Primus

### ISSUE THREAD

**Issue by owenb** [socketstream/socketstream-0.4#21]
The Realtime Transport layer provides an abstraction layer between Prism and Engine.io OR SockJS. As a reminder, Prism is the realtime web server layer of SocketStream 0.4.

You can read more about it here: https://github.com/socketstream/realtime-transport

Since coming up with this idea (which was also in 0.3 to some extent), 3rdEden (who I've got a lot of respect for as an engineer) has created Primus: https://github.com/3rd-Eden/primus

This project is well designed and looks like it's going to be regularly maintained. It also will allow SocketStream to support more transport layers.

Therefore I'd like us to move away from the Realtime Transport idea (and the rtt-*) drivers and use Primus instead.

This will mean changing the Prism code a little and working out the best way for people to switch between transports (e.g. between Engine.io and SockJS).

**Comment by arxpoetica** [comment]
+1

**Comment by paulbjensen** [comment]
I guess the plan would be to implement the following as services on top of primus:
- live-reload
- rpc
- pub/sub

I've done something similar to this with an internal project at Axisto Media, so I would be happy to take this on, unless anyone else wishes to take it on?

**Comment by arxpoetica** [comment]
Take it. I'll help. I'm ready. Just point me in the right direction. :)

**Comment by arxpoetica** [comment]
(Tired of sitting around.)

**Comment by arxpoetica** [comment]
@owenb how would something like https://github.com/codeparty/racer fit (or not fit) into this new paradigm?

**Comment by pocesar** [comment]
@paulbjensen pub/sub is already possible in primus using the http://github.com/cayasso/primus-multiplex, although the methods are not publish/subscribe, but instead are named channels. also, the RPC is similar using primus-eventemitter, without the rpc 2.0 overhead.

**Comment by paulbjensen** [comment]
Thanks for the tip, I'll have a look at it tomorrow.
