### ISSUE TITLE
Authentication and client-server state.

### ISSUE THREAD

**Issue by arxpoetica** [socketstream/socketstream-0.4#22]
One of the trickier aspects of realtime apps is maintaing state and access to different portions of pages and content/action. http://logs.libuv.org/socketstream/2013-07-24#21:56:21.526 <-- this conversation illustrates.

I want to make sure we're tracking this issue, though I don't have a proposed solution at this point. I'm told Racer handles it very, very well, so we may want to look at what they're doing before moving too far into alternative solutions.

**Comment by arxpoetica** [comment]
See also #9, which also deals with mirroring.

**Comment by owenb** [comment]
Hey @americanyak 

I'd very much advise looking into the new Racer. I plan to do the same soon.

I don't think SocketStream should replace the concept of simple RPC calls and Events with Racer, but it could form a good third option. Especially as it should ideally be implemented as just another Realtime Service (no more or less important than any other).

Owen

**Comment by arxpoetica** [comment]
Excellent. I'm glad you have a good handle on it.
