### ISSUE TITLE
Allow explicit control over PACK asset or not PACK assets for each client?

### ISSUE THREAD

**Issue by yiwang** [socketstream/socketstream-0.4#5]
I would like to have options when define client to be able to specify (override the SS_PACK=1, SS_ENV=production) behavior for each client, ideally for each kind of assets (css, code), or even at each file level

This is  useful to figure out problems when css, or js got minified.
especially helpful to just use one port to serve different copies of TEST RUNNER client (minified asset or not) side by side

**Comment by owenb** [comment]
Hey Yi

Thanks for the suggestion.

I think this will happen naturally with what I have in mind.

In 0.4 you define a client and assign it to a variable, e.g. `mainClient`.

Then you can setup your own scripts to do things like:

``` js
if (ss.env === 'production') {
   mainClient.pack();
   adminClient.pack({options: {pass: 'here'}});
}
```

Would this cover everything you have in mind?

Owen
