### ISSUE TITLE
Sending code libraries must not be platform specific

### ISSUE THREAD

**Issue by kraz** [socketstream/socketstream-0.4#8]
`ClientCode.prototype.sendLibrary` and `ClientCode.prototype.sendModule` must not determine if given content is a file by comparing the first character. Main reason - this makes it platform specific (`if (content[0] === '/')` will not work on windows). Second reason - if the content begins with comment block `/* ... */`.

May be something like `ClientCode.prototype.sendLibraryCode` called by `ClientCode.prototype.sendLibrary` will do the job. Or just calculate (or use) absolute paths before loading library content.

**Comment by owenb** [comment]
Hi Krasen

Agreed. This is out of the code now. Still not fully decided how to send assets but it's likely transports and services will just list an array of static files to be included in the build.

SocketStream server will be able to aggregate this into one big Array, which can then be sent through to whichever build system you want to use. Obviously, if you choose to use the build system included in the overal SocketStream framework this will 'just work'.

Cheers,

Owen
